<?php
$content = [
     "HomePage" => [
        'Subject',
        'Sender',
        'Date',
        'Agency-quality content &mdash; without the agency.',
        'Constant Content is the network that connects brands and businesses with thousands of top-quality freelance writers.',
        'Every day, our writers:',
        'Sell articles, marketing copy, product descriptions, blog posts, and more',
        'Partner with brands, agencies, and businesses who value content and copy',
        'Fill any request, whether it’s 10,000 product descriptions or 1 well-crafted article',
        'Earn a larger share per job than on other platforms',
        'Trusted Since 2004',
        '“The team at Constant Content has been a significant contributor of high quality, thoroughly edited assessment material for continuing education courses at LinkedIn Learning. The Constant Content product managers have impressed me with clear, prompt communication and on-schedule delivery of milestones.”',
        '“We’ve used Constant Content to enhance our site’s retail offerings and have been very pleased with the results. The product copy provided was clear, concise and helpful , enabling customers to better engage with our merchandise and make informed purchasing decisions. Constant Content adopted our brand voice and tone, and provided the right type of information in a timely manner..”',
        '“Constant Content has been working on a number of projects for CVS, from product content to long-form articles and informational pages. Constant Content is a great vendor to work with due to their flexibility and speed. The quality has been top notch. I wouldn’t hesitate to recommend them for any content-related project.”',
        'We match businesses’ unique needs with freelance writers that fit them.',
        'The original marketplace for quality, pre-written content.',
        'Writers post thousands of vetted, ready-to-use pieces monthly in the marketplace – and write custom content by request.',
        'Editors who act as co-pilots for writers and buyers.',
        'Our editors offer guidance so writers can produce original content that creates value for businesses.',
        'Content and copywriters that help businesses grow.',
        'Whether it’s a rush job, long-term commitment, or something in between, you can find it here.',
        'Are you an engaging, curious, and self-motivated writer?',
        'Fast-track your career with Constant Content!',
        'Our editorial team provides support and guidance',
        'Focus on your craft &mdash; we’ll take care of project management',
        'Get paid to write content that sparks your interest and highlights your expertise',
        'No project is too big, too small, or too urgent.',
        'Custom Content Writing',
        'You have special requirements that demand subject matter expertise. Our network of writers can make your content engaging, insightful, and original.',
        'Learn more',
        '&LongRightArrow;',
        'Enterprise Services',
        'Do you need project management support? Looking for a strong team of writers? We have the skills, experience, and relationships to deliver great brand-defining content.',
        'Learn more',
        '&LongRightArrow;',
        'Enterprise Services',
        'Do you need project management support? Looking for a strong team of writers? We have the skills, experience, and relationships to deliver great brand-defining content.',
        'Learn more',
        '&LongRightArrow;',
        'Marketplace',
        'Our vast network of diverse writers have created a catalog of unique, ready-to-use articles in every niche imaginable. Choose content for your site today!',
        'Learn more',
        '&LongRightArrow;',
        'If it’s written, we provide it.',
        'Whether you’re looking for sales-oriented copywriting, brand-defining content writing, or something completely different, we have thousands of writers with the expertise and support to create it.',
        'Page copy',
        'Information hierarchy',
        'Branding requirements',
        'Stakeholders review',
        'Stop and start engagements',
        'Product descriptions',
        'Any product, any volume',
        'Easy to manage and export',
        'Unique descriptions optimized for any placement',
        'Whitepapers / eBooks',
        'Technical writing',
        'Subject matter experts',
        'Unique niches',
        'Blog posts',
        'Ready-made content',
        'Custom articles',
        'SEO-friendly',
        'Fast delivery',
        'Need content now? Need content',
        'yesterday',
        'Thousands of pre-written articles are waiting for you in the Constant Content Marketplace.',
        'STEP 1',
        'Sign up here',
        'STEP 2',
        'Fund your account',
        'STEP 3',
        'Purchase articles with 1-click',
        '50,000',
        'happy clients served',
        '50,000+',
        'articles currently in the marketplace',
        '250,000',
        'hours spent editing articles',
        '100%',
        'Unique, human-written content you won’t find anywhere else.',
        'How we compare',
        'High quality writing',
        'Expert Editing',
        'Experience with any topic',
        'Scalable',
        'SEO friendly content',
        'Fast-turnaround',
        'Dedicated writing teams',
        '50k+ articles in marketplace',
        'Get started immediately',
        'Other copy services',
        'High quality writing',
        'Semi-expert Editing',
        'Experience with any topic',
        'Scalable',
        'SEO friendly content',
        'Dedicated writing teams',
        'In-house writers',
        'High quality writing',
        'SEO friendly content',
        'Fast-turnaround',
        'Constant Content',
        'High quality writing',
        'Expert Editing',
        'Experience with any topic',
        'Scalable',
        'SEO friendly content',
        'Fast-turnaround',
        'Dedicated writing teams',
        '50k+ articles in marketplace',
        'Get started immediately',
        'Bottom line',
        'The typical ways of handling content can often be fussy, expensive, and slow to scale. Ready to see the difference that Constant Content can make? Contact us today!',
        'Contact us now',
        'Want to write for us?',
        'About us',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        'Copyright © 2023',
        '&nbsp; | &nbsp;',
        'A Division of Moresby Media Inc. &nbsp; | &nbsp; All rights reserved.',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''

    ]
];

$media =[
     "HomePage" => [
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/beard_guy_laptop.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/2021-logo-linkedin.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/2021-logo-homedepot.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/2021-logo-cvs.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/forwriters_hero_bg.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc-office-group.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc-office-colleagues.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/man_typing_laptop.jpg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc_page_copy.svg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc_product_description.svg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc_whitepaper_ebooks.svg',
    'https://d3u9dosongvh7u.cloudfront.net/resources/1ddfbca7e74ad1571b96d4cff62f760ef59aaad6/images/cc_blog_posts.svg',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''


     ]

];
