<?php
$content = [
     "HomePage" => [
     'Social Media Management, Simplified',
     'helps you discover and schedule content, and manage all your social accounts from one place.',
     'Your super-smart marketing sidekick that will help you grow online everyday.',
     ' Get Started →',
     ' Get Started →',
     'Available on',
     'Available on',
     'Here’s how it works',
     'Discover relevant content based on your topics of interest',
     'Automatically discover articles and images your audience will love, so you can share them to all your social profiles and keep your timelines buzzing!',
     'HOW IT WORKS',
     'Publish content from your own blogs and sites',
     'Keep an eye out for updates from your website, blog or online shops and create quick, beautiful posts for every update to easily share on all your social profiles!',
     'HOW IT WORKS',
     'Pre-schedule all of your content',
     'Schedule all your posts in advance and publish them automatically at the best times or at times chosen by you, saving you tons of time and effort!',
     'HOW IT WORKS',
     'Get tailored posts for every social network',
     'Automagically customize your posts for all your social profiles, taking away the headache of crafting separate posts for each individual social network!',
     'More amazing features…',
     'Get images based on your favourite topics',
     'Use the Chrome extension to share articles you like',
     'Add your own RSS feeds',
     'Get images based on your favourite topics',
     'Use the Chrome extension to share articles you like',
     'Add your own RSS feeds',
     '19M+ Users',
     'from all over the world use',
     '!💥',
     'The application is really good. It is intuitive and it allows me to schedule everything perfectly. Before',
     ', it was painful and it did not work well for me. I had to be sure I had fewer words for Twitter and pictures were not transferring really well.',
     'is doing that for me now and I really appreciate the reporting each week. Works like a charm and I love the ease of the app. I really recommend it for your business!"',
     'Eddie Darac',
     'Gestion BSP',
     'As a small business owner, I strive for the utmost efficiency on a daily basis.',
     'has been a lifesaver when it comes to scheduling our social media! I can sit down and schedule out weeks in advance, freeing me up to focus on sales. Their new calendar view feature is exactly what I was looking for so I can see gaps in my online presence.',
     'has made my life so much easier!"',
     'George Shoemaker',
     'George Shoemaker, Partner, Currency Coffee
     Coffee blender, a taster of everything, sales geek, humanist, libertari',
     'The',
     'app has outstanding publishing features that other social media tools cannot offer. Consistent presentation with video previews, hashtags, and photos make posts look handcrafted every time. Best of all is the affordability of the tool compared to others."',
     'Paul Trinidad',
     'Software Consultant and Social Media Marketer',
     'I am loving using',
     '! As a content creator and social media manager, I have many accounts to manage and my time is extremely valuable. If you are a business owner, you know this, and let me tell you, you need',
     '! The most useful feature for sure is the calendar. It allows me to easily drop in content, so I can spend more time creating and editing, and less time uploading and posting. Being able to visualize all of the content for the month that I have already created allows me to effectively plan out what I still need to create, and seeing it right in front of me helps me protect my precious time! If you are like me and you manage multiple accounts, you can connect all of them and it is super intuitive to use! I highly recommend',
     'to anyone in the digital space!"',
     'Courtney Mixon',
     'Courtney is a social media manager &amp; content creator based out of Atlanta, Georgia. She specializes in fitness marketing and works with big box gyms, boutique fitness studios, wellness spaces, physical therapists and more',
     'I have worked with a lot of social software tools over the years but I find the',
     'app very intuitive and easy to use. My staff and clients can get what they need done when they need it quickly and easily. The reporting adds a lot of value and is delivered on time every week right into our inboxes. I would highly recommend',
     'to any business or marketing professionals."',
     'Jamie',
     'CEO + Founder Howto.Marketing',
     'We have been using social media for promotion for several years and so far we have worked with several different providers. We also started working with',
     'where we found that they offer the most in terms of price. Their platform is very transparent and easy to use. The big advantage is that the add-ons can be added separately and very easily. They offer a lot of add-ons for a very affordable price, but their competition offers half as many for the same price. I recommend their application to anyone who wants an easy way and fast way to create ads. It must also be emphasized that in addition to the typical ways of advertising, it is also possible to arrange specific things so that each user can make their work as easy as possible and choose what they really need."',
     'Damjan Petrič',
     'We offer quality products, tools, accessories, and electrical appliances at affordable prices for hair removal, nail care, cosmetic, and hairdressing services.',
     'has transformed the way I use social media and it saves me a lot of time. Their mentions feature has helped me significantly increase my engagement rate, their analytics are very detailed, and it’s one of the only affordable social media management tools out there!"',
     'MO AL-GHORAIRY',
     'Founder, Turkishware.com',
     'helps you with your end-to-end Social Media process, right from publishing your content to analysing it. It helps me understand what’s working for me and how should I refine my strategies to make the most of Social Media."',
     'Alexandre Augrain',
     'Social Media consultant',
     'I’ve tried many solutions to help me streamline my social media marketing needs and have been very disappointed until I found',
     'App.',
     'not only allows you to schedule your social media posts across all major platform, it also curates content to make it a no-brainer when sharing content specific to your niche. I can’t live without it and highly recommend it."',
     'Bernardo Tirado, PMP',
     'Managing Partner, Welbeck Advisors',
     'If you are looking for the best social media management platform for any industry ranging from education, medical, engineering, non-profit or any field',
     'is the best alternative out there. The hassle-free user interface and the ease of the functionality along with automated reports have helped us boost the organization marketing choices. What I like the best about',
     'is their customer support and the competitors&#x27; analysis which helps Idea Hub Nepal in building a strong strategy to move ahead."',
     'KAMAL SUBEDI',
     'CEO, Idea hub Nepal',
     'I&#x27;ve used Buffer, Hootsuite, Sprout, and several other social media management systems but',
     'has blown them all away. The pricing on',
     'is the best value for my money and the ease and convenience of posting and scheduling on all my social networks from a single app on my phone has saved me hundreds of hours every year!"',
     'Lisa Pietsch',
     'Managing Partner of Tequila Aficionado Media, Publisher of Tequila Aficionado Magazine and is multi-published in both fiction and non-fiction.',
     'As a blogger and social media educator, part of my job is to advise my followers on ways to make their social media marketing more efficient and more effective. There&#x27;s no shortage of social media management tools out there. But for me, what makes',
     'a standout offering is how its robust feature set and streamlined UI make building and scheduling posts effortless. Being able to curate and schedule a ton of posts in one go is such a timesaver, and replying to comments and mentions in one central dashboard is a breeze.',
     '&#x27;s listening tool helps businesses take their social strategy to the next level, allowing you to monitor brand sentiment and keep tabs on the content and performance of competitors - data that can be used to pivot and tweak your own strategy in real-time to outperform your rivals.
     All of',
     '&#x27;s features are underpinned by detailed analytics, with share-ready reports generated in just a few seconds - perfect for disseminating amongst team members.
     If you&#x27;re considering an all-in-one social media management tool for your business,',
     'makes for a really great option, with a generous free trial and competitive pricing options to suit all budgets."',
     'Andrew Macarthy',
     'I’ve been writing about social media marketing and using it to grow my own businesses since 2012. I provide simple and effective strategies that help any business grow using social media.',
     'I have been using',
     'as a social media manager now for almost two years. It has helped me stay on top of all of my social accounts across the board. I love that I can keep up with analytics, as well as schedule posts at the best times all in one easy-to-use location."',
     'Jessica',
     'Social media manager for SohoSpark, a veteran-owned small business providing faux leather journals.',
     'I&#x27;m a U.K. based voiceover artist. So reaching my target client and building ongoing relationships is vital. I’m often recording in the studio, and I never know when the next ‘rush job’ will come in. That means I need to be smart with the time I spend on social media. That’s where',
     'comes in, and it has has quickly become my favourite platform for efficiently planning campaigns and easily reaching the right audience with minimal effort on my part. With just a few clicks my social media work is done for the week!"',
     'Simon Lewis',
     'U.K. based voiceover artist. My role is to breathe emotion, colour and conversation into your brand. To build lasting relationships with you and your customers.',
     'I’m no longer spending a large amount of money on ads that may or may not work. I’m logging into',
     'and finding customers who are already interested in what I’m selling. These customers are liking, commenting, engaging, visiting my site, and buying! A 100% increase in sales!"',
     'Laura',
     'Boutiqueestella Owner',
     'As a small NGO, it can be hard to create consistent social media output, especially when staff and projects change. But',
     'is helping us to plan ahead and the articles/RSS feature means we always have ideas about what content to share. Highly recommended."',
     'Emily Sims',
     'I am the General Manager of Prosper Australia. Our mission is to secure genuine equality of opportunity. We conduct research and educate decision-makers and the general public in the economics of monopoly rent and locational advantage.',
     'I always have that 2:00 AM hour where I have so many tweet ideas, but posting them all of a sudden wouldn&#x27;t be the best way for my account to grow.',
     'completely changed my way of managing my account. I now spend minimum time, while',
     'automatically posts during the &quot;Best-Time&quot; eventually leading to maximum reach"',
     'Priyanka Giri',
     'That CSE Engineer on Twitter',
     'There’s something for everyone, from individuals to agencies.',
     'Annually',
     'Monthly',
     'FREE',
     'PLUS',
     'PREMIUM',
     'VIP',
     'Free',
     'Incase you wanted to try it out',
     '$',
     '7.48',
     '/mo',
     'For solo-preneurs and small businesses',
     '$',
     '37.48',
     '/mo',
     'For medium businesses',
     '$',
     '74.98',
     '/mo',
     'For agencies and larger businesses',
     'FREE',
     'PLUS',
     'PREMIUM',
     'VIP',
     'Free',
     'Incase you wanted to try it out',
     '$',
     '7.48',
     '/mo',
     'For solo-preneurs and small businesses',
     '$',
     '37.48',
     '/mo',
     'For medium businesses',
     '$',
     '74.98',
     '/mo',
     'For agencies and larger businesses' ,
     'Number of accounts linked',
     '3',
     '5',
     '10',
     '25',
     'Supported social networks',
     'SCHEDULING &amp; PUBLISHING',
     'Scheduled posts per account',
     '10',
     '100',
     '100',
     '800',
     'Chrome extension to share articles',
     'Custom Posting Schedule',
     'Bulk Schedule Posts',
     'Schedule with Calendar view',
     'CONTENT CURATION',
     'Article Curation: Unlimited articles recommended for your topics',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Image Curation: Unlimited images recommended for Instagram and Pinterest growth',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Curate content from your own Blogs, Youtube videos and Shopify/Etsy shops',
     'RSS Feed Connect',
     'Up to 5 Feeds',
     'Up to 15 Feeds',
     'Up to 25 Feeds',
     'Hashtag Recommendations',
     'Support for multiple image posts',
     'Autotailored posts for each platform with preview before posting',
     'MENTIONS',
     'Track mentions for your Twitter &amp; Facebook accounts in your team inbox',
     'Send replies to all  the mentions with images and gifs',
     'ANALYTICS',
     '*Social Analytics',
     '*Except Twitter',
     '1 day data',
     '30 days data',
     '30 days data',
     '30 days data',
     '*Advanced Analytics',
     '*Except Twitter',
     '1 day data',
     '90 days data',
     '90 days data',
     '90 days data',
     '*Post Analytics',
     '*Except Twitter',
     'Competitor Analysis - Compare key metrics',
     '2 competitors per social account',
     '20 competitors per social account',
     'PROFILES &amp; TEAM MEMBERS',
     'Profiles',
     'Add &amp; Manage 1 Profile',
     'Add &amp; Manage 2 Profiles (Check add-ons to add more profiles.)',
     'Team Members',
     'Add &amp; Manage 1 Team Member',
     'Add &amp; Manage 2 Team Members per profile (Check add-ons to add more team members.)',
     'OTHERS',
     'Email Support',
     'Priority Support' ,
     'Ad-free experience on mobile',
     '.',
     'Sign Up Free',
     'Sign Up Free',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'FREE',
     'PLUS',
     'PREMIUM',
     'VIP',
     'Free',
     'Incase you wanted to try it out',
     '$',
     '9.99',
     '/mo',
     'For solo-preneurs and small businesses',
     '$',
     '49.99',
     '/mo',
     'For medium businesses',
     '$',
     '99.99',
     '/mo',
     'For agencies and larger businesses',
     'FREE',
     'PLUS',
     'PREMIUM',
     'VIP',
     'Free',
     'Incase you wanted to try it out',
     '$',
     '9.99',
     '/mo',
     'For solo-preneurs and small businesses',
     '$',
     '49.99',
     '/mo',
     'For medium businesses',
     '$',
     '99.99',
     '/mo',
     'For agencies and larger businesses',
     'Number of accounts linked',
     '3',
     '5',
     '10',
     '25',
     'Supported social networks',
     'SCHEDULING &amp; PUBLISHING',
     'Scheduled posts per account',
     '10',
     '100',
     '100',
     '800',
     'Chrome extension to share articles',
     'Custom Posting Schedule',
     'Video Posts Support',
     'Bulk Schedule Posts',
     'Schedule with Calendar view',
     'CONTENT CURATION',
     'Article Curation: Unlimited articles recommended for your topics',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Image Curation: Unlimited images recommended for Instagram and Pinterest growth',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Unlimited',
     'Curate content from your own Blogs, Youtube videos and Shopify/Etsy shops',
     'RSS Feed Connect',
     'Up to 5 Feeds',
     'Up to 15 Feeds',
     'Up to 25 Feeds',
     'Hashtag Recommendations',
     'Support for multiple image posts',
     'Autotailored posts for each platform with preview before posting',
     'MENTIONS',
     'Track mentions for your Twitter &amp; Facebook accounts in your team inbox',
     'Send replies to all  the mentions with images and gifs',
     'ANALYTICS',
     '*Social Analytics',
     '*Except Twitter',
     '1 day data',
     '30 days data',
     '30 days data',
     '30 days data',
     '*Advanced Analytics',
     '*Except Twitter',
     '1 day data',
     '90 days data',
     '90 days data',
     '90 days data',
     '*Post Analytics',
     '*Except Twitter',
     'Competitor Analysis - Compare key metrics',
     '2 competitors per social account',
     '20 competitors per social account',
     'PROFILES &amp; TEAM MEMBERS',
     'Profiles',
     'Add &amp; Manage 1 Profile',
     'Add &amp; Manage 2 Profiles (Check add-ons to add more profiles.)',
     'Team Members',
     'Add &amp; Manage 1 Team Member',
     'Add &amp; Manage 2 Team Members per profile (Check add-ons to add more team members.)',
     'OTHERS',
     'Email Support',
     'Priority Support',
     'Ad-free experience on mobile',
     'Sign Up Free',
     'Sign Up Free',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Buy Now',
     'Let’s Go!',
     'Get Started →',
     'Get Started →',
     'Don’t have an account?',
     'Signup here.',
     '&nbsp;Sign in with Facebook',
     '&nbsp;Sign in with Twitter',
     'Already have an account?',
     'Login here',
     '&nbsp;Sign up with Facebook',
     '&nbsp;Sign up with Twitter',
     'By signing up, I agree to',
     '’s',
     'Terms of Service',
     'Let’s Go!',
     'Email Address',
     'Password',
     'Log in',
     'Create an account',
     'Forgot password',
     'Reset password',
     'Just let us know the email you use to sign in to',
     'and we’ll help you get your password back.',
     'Email Address',
     'Send Password Reset Email',
     'Take me back to login',
     'Recovery Email Sent!',
     'Please check your email within next 15 minutes for next steps to reset your password.',
     'If you can&#x27;t see the mail, it might be in your spam folder, or your',
     'Take me back to login',
     'Let’s Go!',
     '&nbsp;Sign in with Facebook',
     '&nbsp;Sign in with Twitter',
     '&nbsp;Sign in with Email',
     'Login with Instagram has been deprecated:&nbsp',
     'Read more',
     'Don’t have an account?',
     'Register here',
     'Let’s Get your Account Set Up',
     '.',
     'Full Name',
     '.',
     'Email Address',
     'Password',
     'Confirm Password',
     'Register',
     'By signing up, I agree to',
     '’s',
     'Terms of Service',
     'Already have an account?',
     'Login here',
     'Let’s Go!',
     'Already have an account?',
     'Login here',
     '&nbsp;Sign up with Facebook',
     '&nbsp;Sign up with Twitter',
     '&nbsp;Sign up with Email',
     'By signing up, I agree to',
     '’s',
     'Terms of Service',
     'Terms Of Service',
     'Privacy Policy',
     'Refund policy',
     'about us',
     'Follow us on',
     '.',
     '© 2023',
     'Inc. All rights reserved.',
     ''
    ]
];

$media =[
     "HomePage" => [
      '/assets/images/landing/logo-full.70cd4daf.svg',
      '/assets/images/landing/logo-symbol.f9aaf2be.svg',
      'assets/images/landing/how-it-works-2@3x.7356d687.jpg',
      'assets/images/landing/how-it-works-3@3x.f1efb507.jpg',
      'assets/images/landing/how-it-works-4@3x.2792b7ea.jpg',
      'assets/images/landing/how-it-works-5@3x.6262cccc.jpg',
      'assets/images/landing/tabs-fold1/carousel-slide-1@3x.9ded932f.png',
      'assets/images/landing/tabs-fold1/carousel-slide-2@3x.0b6a756b.png',
      'assets/images/landing/tabs-fold1/carousel-slide-3@3x.8f7ba31f.png',
      'assets/images/landing/testimonials/george.567318f0.jpg',
      'assets/images/landing/testimonials/trinidad.7341e3b1.png',
      'assets/images/landing/testimonials/courtney_mixon.28fa431c.jpeg',
       'assets/images/landing/testimonials/jamie.dddcc385.jpeg',
       'assets/images/landing/testimonials/nega.ddd511cb.jpg',
       'assets/images/landing/testimonials/MoAlGhorairy.37c783f6.jpg',
       'assets/images/landing/testimonials/alexandre.0b6cbf2f.jpg',
       'assets/images/landing/testimonials/BernardoTirado.6ef36e3a.jpg',
       'assets/images/landing/testimonials/KamalSubedi.82e96cde.jpg',
       'assets/images/landing/testimonials/lisa-pietsch.1a100826.jpeg',
       'assets/images/landing/testimonials/AndrewMacarthy.0d3d1713.jpg',
       'assets/images/landing/testimonials/Sohospark.b4e53d0a.png',
       'assets/images/landing/testimonials/SimonLewis.80af4d84.png',
       'assets/images/landing/testimonials/laura.9a993008.jpg',
       'assets/images/landing/testimonials/emily-sims.df8b3d06.png',
       'assets/images/landing/testimonials/priyanka-giri.96a9d7b9.jpeg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/youtube-logo.ed6245b4.svg',
       'assets/images/pricing/v3/wordpress-logo.f64d00c9.svg',
       'assets/images/pricing/v3/shopify-logo.c6f4c97e.svg',
       'assets/images/pricing/v3/etsy-logo.969ce11d.svg',
       'assets/images/pricing/v3/blog-logo.ec2393d6.svg',
       'assets/images/pricing/v3/twitch-logo.3334d3a1.svg',
       'assets/images/pricing/v3/vimeo-logo.2fad3aa7.svg',
       'assets/images/pricing/v3/500-px-logo.f22a826e.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/dash-symbol.3fc9f4ae.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/pricing/v3/tick-symbol.b0426e11.svg',
       'assets/images/features/features-mentions-main-image@2x.47061144.png',
       'assets/images/landing/logo-full.70cd4daf.svg',
       'assets/images/landing/logo-full.70cd4daf.svg',
       '/assets/images/landing/symbol@2x.cc77b90f.png',
       '/assets/images/landing/symbol@2x.cc77b90f.png',
       '',
       '',
       '',
       '',
       '',
       '',
       ''



     ]

];
