<?php
$content = [
     "HomePage" => [
        'Quality content at scale.',
        'Access content writing services from a network of specialized, professional writers.',
        'Trusted by industry leaders such as:',
        'Content that works',
        'Whatever industry you&rsquo;re in, you need expert writers who can engage your audience. We&rsquo;ll find those writers for you.',
        'Agencies',
        'We partner with agencies to support the content and copywriting needs of their clients.',
        'Publishers',
        'We support digital publishers by writing targeted content for their different sites at scale.',
        'eCommerce',
        'We write product descriptions, web pages, and category pages with an emphasis on SEO.',
        'Brands',
        'We develop your voice and tone and write custom content for brands big and small.',
        'Content You Can Trust',
        'Testimonials',
        'Natalie Winzer',
        'B2C Marketing Manager',
        'has been a great partner for us in providing relevant, helpful information to our customers.',
        'Sam Kerstetter',
        'Senior Content Marketing Manager',
        'The CW team is nimble and incredibly helpful. They not only help you execute on your vision, they truly endeavor to understand what your editorial needs are and how their team can best help meet these needs. They ensure the content CW is creating is not only engaging, but also purposeful.',
        'Katie Hudson',
        'Creative Manager',
        'Working with',
        'has been incredibly helpful for our brand. By relying on their team, we&#x27;ve been able to launch a blog, improve our SEO, and create new product descriptions quickly. I&#x27;d highly recommend working with them',
        'Chris Freitas',
        'Director, Business Development',
        'The',
        'team has been very professional, prompt, and proactive. I researched diligently for content creators and CW was by far the best option.',
        'Michael Barber',
        'Director of Marketing',
        'There are so many outlets to create content these days. We&#x27;re fortunate to have found a partner in',
        'that enables us to move quickly, trust their team to execute reliably, and publish great content.',
        'Alex Neal',
        'President',
        'has been a great cost effective solution for us to get relevant original content in a timely manner. I would definitely recommend them.',
        'Steven Collinge',
        'Founder &amp; CEO',
        'Since the very moment we started working with',
        'almost 5 years ago now, we found them to be just great to work with. Their services have been vital to our growth and the constant support is why we continue to enjoy every single communication and have done for all these years.',
        'Matthew Rickerby',
        'Director of Marketing',
        'have been such a help to our marketing team, they&#x27;ve created content that has helped us rank better for key search terms and have driven lots of organic traffic.',
        'Aaron Rosenthal',
        'Director of Marketing',
        'E-file.com was named the 79th fastest growing private company by Inc. Magazine.',
        'helped E-file.com obtain this growth without employing a single full-time writer on staff.',
        'Chris Fasano',
        'Director of Marketing',
        'We needed top notch quality writing and in volume, which',
        'provides for us week in and week out. We are very pleased with',
        '’ work thus far.',
        'Previous',
        'Next',
        'Trusted by the World s Best Companies',
        'Content Marketing Resources',
        'Check out some of our latest blogs, white papers, and case studies to see how we help writers and clients
        work together to achieve success.',
        'Blog Posts',
        'How an Author Bio Page Can Boost Your Blog’s Performance',
        'September 6th, 2023',
        'There are&nbsp;1.9 billion websites worldwide, and more than 600 million are blogs. That&#8217;s a lot of content vying for attention. &#8230;',
        'White Papers',
        'How to Write an Effective Video Script',
        'June 1st, 2023',
        'Creating an excellent video begins with a high-quality script. Uncover everything you need to know about writing a video script that engages and achieves your goals.',
        'Learn more',
        'Case Studies',
        'Points Group Agency &amp;',
        'frees up Points Group team&#x27;s bandwidth and helps increase healthcare clients&#x27; online traffic.',
        'Set up your account and order content on demand with no commitments.',
        'Self Service',
        'Starting at $99 per piece. Sign up to view full pricing information.',
        'Create Free Account',
        'Included with our Self-Service platform:',
        'Free Platform Access',
        '100% Satisfaction Guaranteed',
        'Editing',
        'Proofing',
        'Premium Customer Support',
        'Plagiarism Detection',
        '2 Rounds of Revisions',
        '3 Business-day Review Period',
        'Managed Services',
        'You’ll have a dedicated content success specialist handle every step of the process for you.',
        'Packages are customized to meet your unique needs.',
        'Request a quote',
        'Includes all Self-Service platform amenities plus:',
        'Dedicated Account Management',
        'Quality assurance',
        'Account support',
        'Order management',
        'Monthly Topic Pitching',
        'Industry relevant topics',
        'SEO-compliant',
        'Writer Team Retention',
        'Maintain brand messaging',
        'Consistent voicing',
        'Extended Review Period',
        '6-10 business-days',
        'Unlimited Revisions',
        'Content Calendar Tracking',
        'Contact Us',
        'Let&rsquo;s Discuss Your Content Goals',
        'Scale content with a dedicated account&nbsp;manager',
        'Managed Account Benefits',
        '&mdash; Custom writer vetting and management',
        '&mdash; High volume, high quality content',
        '&mdash; Consistent publishing schedules',
        '&mdash; Premium customer support',
        'pages',
        'terms of service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        '148 Mercer Street, 2nd FL.<br>New York, NY 10012',
        '212-235-1103',
        '800-891-0553',
        'Weekdays 9am-6pm ET',
        'Get smarter! Sign&nbsp;up for our newsletter',
        'Email Address ',
        '&copy; All rights reserved',
        'LLC',
        ''
       
    ]
];

$media =[
     "HomePage" => [
    'http://localhost/contentwriters.com/static/global/img-design/xlogo.png',
    'http://localhost/contentwriters.com/static/website/img/home19/expedia.png',
    'http://localhost/contentwriters.com//static/website/img/home19/questex.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/aac%402x.png',
    'http://localhost/contentwriters.com/static/website/img/home19/legalzoom.png',
    'http://localhost/contentwriters.com/static/website/img/home19/turn5.png',
    'http://localhost/contentwriters.com/static/website/img/home19/skillsoft-navy_LOGO.png',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_agencies.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_publishers.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_ecommerce.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_brands.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_check.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_edit.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_cal.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_chart.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_idea.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_expert.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_drafts.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_award.svg',
    'http://localhost/contentwriters.com/static/website/img/home19/icon_speech.svg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/ihire.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/img990.png',
    'http://localhost/contentwriters.com/upload/testimonial_logos/RoadRunnerSports_Logo.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/download_Lnnrqfi.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/urbanstems.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/0_QBChaGP.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/KBI.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/594.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/solv_SnkNgza.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/img0030.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/campusbooks.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/img03030.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/gdp.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/img3532.jpg',
    'http://localhost/contentwriters.com/upload/testimonial_logos/skubana.png',
    'http://localhost/contentwriters.com/upload/testimonial_logos/logo_lg.png',
    'http://localhost/contentwriters.com/upload/testimonial_logos/tpp.png',
    'http://localhost/contentwriters.com/upload/testimonial_portraits/img83738.jpg',
    'http://localhost/contentwriters.com/static/website/img/landing19/arrow-left.svg',
    'http://localhost/contentwriters.com/static/website/img/landing19/arrow-right.svg',
    'http://localhost/contentwriters.com/blog/author-bio-page-boost-blog-performance/cheerfulyoungmalestudentenjoyingtrainingwebinaronlaptopcomputer/',
    'http://localhost/contentwriters.com/upload/website_whitepapers/2023_WP_image-80_nhVtzgh.webp',
    'http://localhost/contentwriters.com/upload/website_success_stories/Case_Study_2023_thumbnails_19.png',
    'http://localhost/contentwriters.com/static/global/img/xlogo_black.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''


     ]

];
