<?php
$content = [
     "HomePage" => [
        'we are content marketing enthusiasts',
        'You need Quality blog writing services to power seo',
        'Our platform exquisitely combines human and machine to make blog and content creation happen.',
        'It’s awesome. Keep reading.',
        'Content writing services for marketers and seos',
        'We’re not Apple, we’re Applebee’s.',
        '’s blog and content writing service is like a good cheeseburger: appealing to most humans and it gets the job done.',
        'Create tons of publish-ready content with the best content writing service. AI makes it faster and cheaper',
        '.',
        'Get blog posts , articles, web copy, local landing pages , and big content projects.',
        'The best agencies and marketers choose',
        'to deliver quality content at scale.',
        'Astrology to zoology, we scratch the content niche. Use',
        'to create content for yourself or your clients.',
        'Need managed service? Our enterprise team "makes problems go away." (Actual client quote)',
        'If you prefer a 100% human blog writing service with no AI anywhere in the process, we can do that too.',
        'Content creation',
        'We incorporate human writers and editors at strategic points in the process, so you get human content delivered faster and cheaper thanks to AI.',
        'See how it works',
        'Solutions for Agencies',
        'We’re focused on helping agencies grow through content. Our platform enables scale and quality. Custom account management solutions available.',
        'Enterprise content',
        'Custom solutions for publishers, agencies, and in-house marketers who need more content than the average bear and worker bees to handle the rest.',
        'Feel the Love',
        'I’m in love with your service. I added another topic the other day and got a post back in less than 10 hours that felt like the writer read my mind.',
        'BJ E.',
        'Enterprise Agency client',
        'After just two months of consistent blog posting with content from',
        ', we ranked on the first page of Google for four of our critical keywords.',
        'Ben A.',
        'Manufacturing client',
        'The writers are fantastic, and quickly turned around edit requests. The results speak for themselves—our organic traffic is up 46% in the past 9 months.',
        'Mark z.',
        'E-commerce client',
        'Pricing.',
        'Enticing.',
        'Self-serve platform',
        '$0.06',
        '/word',
        '$49.50/mo platform fee',
        'Waived for your first month',
        'Original high-quality content for SEO. Created by humans. AI makes it faster and cheaper.',
        'Enterprise',
        'Custom pricing',
        '100 articles/month min.',
        'No platform fee',
        'We manage',
        'for you. Get high-quality content delivered when and how you need it.',
        'Features include:',
        'Pay as you go',
        'Proofreading for spelling and grammar',
        'Google docs delivery',
        'Content types:',
        'Blog posts',
        'Website content',
        'Live chat support',
        '2 - 4 day turnaround',
        'Custom workflows',
        'A dedicated account manager',
        'Provide a custom style guide',
        'Request revisions',
        'Features include:',
        'No platform fee',
        'Proofreading for spelling and grammar',
        'Google docs delivery',
        'Custom content types, including:',
        'Blog posts',
        'Website content',
        'Live chat support',
        'Flexible turnaround',
        'A dedicated account manager',
        'Provide a custom style guide',
        'Request revisions',
        'Questions? Check out',
        'contact us',
        'Pages',
        'Refund policy',
        'delivery policy',
        'about us',
        'Support',
        'Contact Us',
        'ADDRESS',
        '1700 Lincoln St.',
        '17th Floor',
        'Denver, CO 80203',
        'Privacy Policy',
        'Terms of Service',
        '© 2023',
        '. All Rights Reserved.',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''


    ]
];

$media =[
     "HomePage" => [
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg-500x128.png',
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg-500x128.png',
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg-768x196.png',
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg-600x153.png',
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg-300x77.png',
    '/wp-content/uploads/2018/08/verblio-logo_horizontal_RGB_neg.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x-500x445.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x-768x684.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x-600x534.png',
    '/wp-content/uploads/2018/09/verblio_violet-Artboard-43@2x-300x267.png',
    '/wp-content/uploads/2018/10/verblio_content-creation-2@2x.png',
    '/wp-content/uploads/2018/10/verblio_content-creation-2@2x.png',
    '/wp-content/uploads/2018/10/verblio_content-creation-2@2x-500x444.png',
    '/wp-content/uploads/2018/10/verblio_content-creation-2@2x-768x682.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x-500x445.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x-768x684.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x-600x534.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x-600x534.png',
    '/wp-content/uploads/2018/09/verblio_pink-strategy-approach@2x-300x267.png',
    '/wp-content/uploads/2019/12/verblio_violet-_content-marketing.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white-500x131.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white-768x201.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white-600x157.png',
    '/wp-content/uploads/2018/09/verblio-logo_horizontal_one-color_white-300x79.png'


     ]

];
