<?php
$content = [
     "HomePage" => [
          
     "Quality content, on demand",
     "Get a vetted writer to deliver quality content, fast. 
     From blog posts to ad copy (and everything in between), we’ve got you covered.",
     "Money-back guarantee for your first 4,000 words.",
     "Free revisions and rewrites.",
     "Powering content for the world's top brands",
     "How it works",
     "Submit a content request in under 5 mins. We handle the rest.",
     "“iDraft takes care of the whole copywriting process end to end. They've been great at helping us get our larger pipeline of content out quickly.”",
     "Alycia Harris",
     "1.",
     "Growth Marketing Manager &#64; Opencare",
     "Submit your content request",
     "Use our brief builder or upload your own brief on our platform.",
     "Utilize our Zapier integration to submit your requests directly from tools such as Asana or Monday.",
     "2.",
     "A writer matched in 24 hrs. and working on your content",
     "We'll match you with the best writer in under 24 hrs. and have them start working on your brief.",
     "3.",
     "Collaborate with your matched writer via our in-app messaging tool.",
     "Publish ready content delivered. Free revisions and rewrites.",
     "By the stated deadline get your publish-ready content piece back.",
     "Need tweaks&#63; We offer free revisions and rewrites until you're happy. All self-served via our app.",
     "AI-powered workflows",
     "We've built tools to help you with idea generation, brief creation, collaboration, and more. All 100% free.",
     "An extended writing team",
     "Uber-style ratings will help our algorithms assemble a fractional writing team that consistently works for you and knows your brand and editorial guidelines.",
     "Tech-enabled collaboration",
     "Idea generator and brief builder",
     "Use our free AI tools to generate content ideas, create a brief or generate article outlines.",
     "“iDraft has been instrumental in helping us scale our content while maintaining high quality that both users and search engines love. We've beaten all projections thanks to the fantastic team at iDraft.",
     "Krinal Mehta",
     "Senior SEO Manager &#64; Freshbooks",
     "Vetted writers covering",
     "a broad range of topic and types",
     "Consistent high-quality",
     "Vetted top 1% of writers",
     "A typical writer on our platform has a 4.8 star customer rating and a rewrite rate of &lt;1%. We rigorously vet writers and only accept the best.",
     "Over 1,000 writers to scale",
     "We have over 1,000 writers spanning the US/Canada, UK and AU/NZ to handle various dialects and regional nuances.",
     "Wide-range of topics/types",
     "Our writers come with experience in a variety of topics and content types. Not sure if we handle your niche&#63;",
     "Contact us",
     "on live-chat.",
     "Plagiarism detection",
     "Every content piece goes through plagiarism detection using Copyscape before it's delivered to you.",
     "Human written content",
     "We pass content through our AI content detection tool to ensure it's 100% human generated.",
     "“With iDraft, we found a risk-free solution for high-quality content. If there is ever any issue with the writing, the team is quick to provide revisions, &amp; even find a new writer if it's really not a good fit.”",
     "Glenn Paquette",
     "CEO &#64; Atomic Agency",
     "Simple",
     "pay-as-you-use pricing",
     "No contracts. No commitments.",
     "If we don't crush it, you get your money back. We’ll refund your purchase (up to the first 4000 words).",
     "plan",
     "USD 0.10",
     "/word",
     "A blog post of 1,000 words will cost you USD 100. Back to you in 5 days",
     "“iDraft is the best writing service I’ve ever used. We’ve published in publications like the Wall Street Journal and Inc Magazine.”",
     "Lauren Proctor",
     "Marketer &#64; Jobbatical",
     "What's included&#63;",
     "- Research",
     "- Royalty-free images",
     "- Unlimited revisions",
     "- Live-chat support",
     "Looking for managed services or high volume discounts&#63; Contact us.",
     "FAQ",
     "Your most common questions about iDraft, answered.",
     "How does it work?", 
     "It takes 30 seconds to sign up for a iDraft account and get access to your content creation dashboard. Create a content brief and get matched with the best writer to take it on. You can message your writers directly through the platform and track their progress. If you&#039;d like any revisions made, you can do so free of charge!",
     "What types of content do you create?",
     "The writers at iDraft can take on a variety of content formats, essentially anything written. Primarily we handle blog posts, social posts, web page copy, and marketing emails. If there&#039;s something specific you&#039;re looking for, email us at support@",
     "or shoot us a message on chat and we&#039;ll see if we can help you with your specific content needs!",
     "How many pieces of content will I get?",
     "With our flexible pay-as-you-go pricing, you can request as many content pieces as you&#039;d like to be worked on in parallel. A content piece that&#039;s 1,000 words in length will be returned back in five days. Revisions and rewrites are not charged extra.",
     "Do you do research?",
     "We do preliminary research on all content using publicly available information and include sources for any facts or statistics we quote. Please specify your requirements for citations if applicable.",
     "Do you offer edits or revisions?",
     "Creating perfect content the first time can be tough, so we offer free revisions on any content you receive in case you&#039;d like some tweaks. Our goal is to get you content that you&#039;re happy with and delivers value to your readers!",
     "Sign up for our newsletter",
     "Join our monthly email with marketing insights and feature updates.",
     "Something went wrong&#33; Try submitting form once again.",
     " Something went wrong&#33; Try submitting form once again.",
     "Subscribe",
     "Terms Of Service",
     "Privacy Policy",
     "Refund policy",
     "delivery policy",
     "about us",
     "© 2023 CONTENTFLY INC.  All rights reserved."  


     ]
];

$media =[
     "HomePage" => [
    "https://assets.ycodeapp.com/assets/app18099/Images/Wn7s504jcRZyX58DurHjVKwABHq0hUOVJl1ZZm1L-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/Yeel5zFaCdQZlqoI8HZM9cX4ycI8tO4PbKp86pDC-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/E6PZZGoamgDvXWIB68nf3WVrXr74mSa6ZNQgfFfn-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/KdCYjA7rQE4AsWLhzEjwOKzVgm9bYspSfLZdJxS3-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/DSc1RoChocbeBUXiE0QTR6J4IVd4A0Lw00wt1P1Z-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/gZ6Y5iPVaE4M5Lm8jDHprbaRJimWGOIKmoDQqyOO-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/Yeel5zFaCdQZlqoI8HZM9cX4ycI8tO4PbKp86pDC-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/E6PZZGoamgDvXWIB68nf3WVrXr74mSa6ZNQgfFfn-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/KdCYjA7rQE4AsWLhzEjwOKzVgm9bYspSfLZdJxS3-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/DSc1RoChocbeBUXiE0QTR6J4IVd4A0Lw00wt1P1Z-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/gZ6Y5iPVaE4M5Lm8jDHprbaRJimWGOIKmoDQqyOO-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/Yeel5zFaCdQZlqoI8HZM9cX4ycI8tO4PbKp86pDC-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/E6PZZGoamgDvXWIB68nf3WVrXr74mSa6ZNQgfFfn-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/KdCYjA7rQE4AsWLhzEjwOKzVgm9bYspSfLZdJxS3-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/DSc1RoChocbeBUXiE0QTR6J4IVd4A0Lw00wt1P1Z-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/gZ6Y5iPVaE4M5Lm8jDHprbaRJimWGOIKmoDQqyOO-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/Yeel5zFaCdQZlqoI8HZM9cX4ycI8tO4PbKp86pDC-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/E6PZZGoamgDvXWIB68nf3WVrXr74mSa6ZNQgfFfn-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/KdCYjA7rQE4AsWLhzEjwOKzVgm9bYspSfLZdJxS3-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/DSc1RoChocbeBUXiE0QTR6J4IVd4A0Lw00wt1P1Z-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/gZ6Y5iPVaE4M5Lm8jDHprbaRJimWGOIKmoDQqyOO-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/371NCkIr589t61sDNRgxPLRXreZXBEX5fb6vawz5-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/rbtBcZpzdkQ22mAIPuYLAWPlgtvjdsUQyfxjRv9z-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/ht1J2vtdaMT1shUl1yJLywU5amWcvSZQLkHMdlp5-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/jImAKGtIN7BgUhT33TpUgM7anCho99A5Og01QwaK-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/PBhHh1nXQVMDQQYyJWqcbZHtSyqCWmCtY12k5ihH-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/371NCkIr589t61sDNRgxPLRXreZXBEX5fb6vawz5-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/rbtBcZpzdkQ22mAIPuYLAWPlgtvjdsUQyfxjRv9z-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/ht1J2vtdaMT1shUl1yJLywU5amWcvSZQLkHMdlp5-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/jImAKGtIN7BgUhT33TpUgM7anCho99A5Og01QwaK-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/PBhHh1nXQVMDQQYyJWqcbZHtSyqCWmCtY12k5ihH-published.svg",
    "https://assets.ycodeapp.com/assets/app18099/Videos/NscmNfRO8MRILHcM5lfjBOGD9Edej6aIRFCunEs2-published.mp4",
    "https://assets.ycodeapp.com/assets/app18099/Images/PHKzVAJ50rjziLF6sdfp50iADkbI5XA0Ejuf4PgH.svg",
    "https://assets.ycodeapp.com/assets/app18099/Images/tCggwd6G0Dbuw26Pi4c3u5CJtHQV1VFXMTAg8GKi-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/nS7HFT3tvTV2rs7YxVky6IvhIKNF1wxkKXeFawKR-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/laetE2UKIkj30m9wdI6KKAfArwGujrPUsiOJQw4i-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/KHqq8ubvLrNq6FyyyVIShh4nutQJl2b5fj3CLMys-published.png",
    "https://assets.ycodeapp.com/assets/app18099/Images/y5SZNVaFzNB8TKSN0K3tI3pzah1kYe5sRp5GIgUU-published.png",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
     ]

];
