<?php include_once ('website.php'); ?>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="$2y$10$mBD3l6SKSCYGQfjB7q/kiuzES0XNkJxGVdeW2bZJuXC.HHGJqjA.K">
    <link rel="icon" type="image/png" sizes="32x32" href="https://assets.ycodeapp.com/assets/app18099/favicons/2ajxoS6msGgyxV4WHBWzz5v0nLBmnrOwCydB4zvU.png">
    <link rel="apple-touch-icon" sizes="256x256" href="https://assets.ycodeapp.com/assets/app18099/webclips/TSYV8uFOk8YnhRjBmyXUpCkCtanrEvzPZVe7fOr4.png">
    <link href="/css/builder/ycode-generated.css?id=b5351184e166f07e2806" rel="stylesheet">
    <link href="/published/main.css?id=1694550187" rel="stylesheet">
    <link rel="canonical" href="">
    <title>Terms &amp; Conditions</title>
    <meta name="description" content="We pair cutting-edge technology with vetted writers to deliver quality content, fast. From blogs to ad copy and everything in between, we’ve got you covered.">
    <meta property="og:image" content="https://assets.ycodeapp.com/assets/app18099/Images/OhzQ5btkWGUQ6BSl89mayGSpYqQhh0oaP2XkStmK-published.png">
    <meta property="twitter:image" content="https://assets.ycodeapp.com/assets/app18099/Images/OhzQ5btkWGUQ6BSl89mayGSpYqQhh0oaP2XkStmK-published.png">
    <meta content="summary_large_image" name="twitter:card">
    <meta property="og:title" content="On-Demand Content Writing — Blogs, Email, Social">
    <meta property="twitter:title" content="On-Demand Content Writing — Blogs, Email, Social">
    <meta property="og:description" content="We pair you with vetted writers to deliver quality content,&nbsp;fast.">
    <meta property="twitter:description" content="We pair you with vetted writers to deliver quality content,&nbsp;fast."> 
</head>
<body class="min-h-[100%] font-manrope bg-[#E5E5E5] bg-opacity-[10%]">
    <div class="contents" id="ycode-generated-app">
        <div class="contents" id="inside" :key="key">
            <section class="pt-[20px] pb-[20px] sticky top-[0px] z-[100] bg-center bg-contain">
                <div class="mr-[auto] ml-[auto] pr-[32px] pl-[32px] md:pr-[24px] md:pl-[24px] max-w-[1536px] rounded-[0px] border-none">
                    <div class="grid grid-cols-3 bg-[white] items-center pt-[8px] pb-[8px] pr-[8px] pl-[8px] lg:grid-cols-2 rounded-[12px] bg-[#FFFFFF] bg-opacity-[100%]" data-animation-load="mqr1d9oyc" data-animation-id-mqr1d9oyc>
                        <div class="flex justify-start pl-[12px]">
                            <a class="pt-[14px] pr-[14px] pb-[14px] pl-[14px] hover:opacity-[80%]" href="/" current> <img class="h-[24px]" src="https://assets.ycodeapp.com/assets/app18099/Images/Wn7s504jcRZyX58DurHjVKwABHq0hUOVJl1ZZm1L-published.svg" srcset=", https://assets.ycodeapp.com/assets/app18099/Images/Wn7s504jcRZyX58DurHjVKwABHq0hUOVJl1ZZm1L-published.svg w" sizes="(max-width: px) 100vw, px"></a>
                        </div>
                        <div class="flex items-center justify-center gap-[40px] lg:hidden"> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[#000000] text-opacity-[100%]" href="/#features">Features</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[#000000] text-opacity-[100%]" href="/#pricing">Pricing</a> </div>
                        <div class="flex items-center justify-end lg:gap-[12px]">
                            <button v-show="showHideElements['toggle-mobile-menu']" @click='triggerWorkflow($event)' class="tracking-[0.025em] leading-[1.25rem] border-[transparent] border-[1px] border-solid focus:outline-none pr-[24px] pl-[24px] text-[16px] pt-[16px] pb-[16px] font-medium text-[black] rounded-[8px] lg:pl-[16px] lg:pr-[16px] lg:bg-[black] lg:text-[white] lg:hover:bg-[black] hidden lg:flex lg:items-center lg:justify-center bg-[#75FB92] bg-opacity-[100%] hover:bg-[#69E283] hover:bg-opacity-[100%] lg:bg-[#000000] lg:bg-opacity-[100%] lg:hover:bg-[#000000] lg:hover:bg-opacity-[100%] border-[#000000] border-opacity-[0%] text-[#000000] text-opacity-[100%] lg:text-[#FFFFFF] lg:text-opacity-[100%]" id="toggle-mobile-menu" type="button" data-animation-click="etw25u2wf"> <i class="lg:w-[20px]"><svg viewbox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.75 5.75H19.25"></path>
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.75 18.25H19.25"></path>
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.75 12H19.25"></path>
                                </svg></i></button>
                            <a class="tracking-[0.025em] leading-[1.25rem] border-[transparent] border-[1px] border-solid focus:outline-none pr-[24px] pl-[24px] text-[16px] pt-[16px] pb-[16px] font-medium text-[black] rounded-[8px] lg:hidden flex items-center justify-center gap-[8px] transform hover:bg-black hover:text-white bg-[#E5FE9B] bg-opacity-[100%] border-[#000000] border-opacity-[0%] text-[#000000] text-opacity-[100%]" href="/contact"> <span>Contact</span> </a>
                        </div>
                    </div>
                    <div v-show="showHideElements['mobile-menu']" v-cloak class="absolute right-[0px] left-[0px] ml-[32px] mr-[32px] mt-[12px] pt-[24px] pr-[24px] pb-[24px] pl-[24px] bg-[white] hidden md:block lg:block rounded-[12px] md:ml-[24px] md:mr-[24px] bg-[#FFFFFF] bg-opacity-[100%]" id="mobile-menu" data-animation-id-weilbpkl5>
                        <div class="flex flex-col items-center justify-center gap-[20px] lg:items-stretch lg:text-center"> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[#000000] text-opacity-[100%]" href="/#features">Features</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[#000000] text-opacity-[100%]" href="/#pricing">Pricing</a>
                            <a class="tracking-[0.025em] leading-[1.25rem] border-[transparent] border-[1px] border-solid focus:outline-none pr-[24px] pl-[24px] text-[16px] pt-[16px] pb-[16px] flex items-center gap-[8px] font-medium text-[black] rounded-[8px] lg:justify-center sm:bg-[black] bg-[#75FB92] bg-opacity-[100%] sm:bg-[#000000] sm:bg-opacity-[100%] border-[#000000] border-opacity-[0%] text-[#000000] text-opacity-[100%]" href="/contact"> <span class="text-[16px] sm:text-[white] sm:text-[#FFFFFF] sm:text-opacity-[100%]">Contact</span> </a>
                        </div>
                    </div>
                </div>
            </section>
            <div class="mt-[72px] ml-[auto] mr-[auto] max-w-[768px] space-y-[12px]">
                <div itemprop="mainContentOfPage">
                    <div class="general_articlePageArticle__pN2wm" itemscope="" itemtype="https://schema.org/Article">
                        <h1 class="font-semibold tracking-[-0.025em] text-[60px] leading-[1.15] sm:text-[36px]" itemprop="name">Terms &amp; Conditions</h1>
                        <p class="general_articlePageUpdatedDate__ByuD2">Last updated September 4, 2023</p>
                        <div itemprop="text" class="content_container__Cv_d6">
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">ContentFly Inc d/b/a iDraft</strong></span><span class="atlas-leaf"> (“</span><span class="atlas-leaf"><strong class="atlas-leaf">iDraft</strong></span><span class="atlas-leaf">”) provides a content generation service through its website located at <?=$host?> (“</span><span class="atlas-leaf"><strong class="atlas-leaf">Site,</strong></span><span class="atlas-leaf">” and together with such service, including any updated or new features, functionality and technology, collectively the “</span><span class="atlas-leaf"><strong class="atlas-leaf">Services</strong></span><span class="atlas-leaf">”). The Services may be provided on a subscription basis under specific subscription plans (“</span><span class="atlas-leaf"><strong class="atlas-leaf">Subscription Plan</strong></span><span class="atlas-leaf">”) or on a usage basis under specific prepaid usage plans (“</span><span class="atlas-leaf"><strong class="atlas-leaf">Usage Plan</strong></span><span class="atlas-leaf">,” and with the Subscription Plan, collectively, “</span><span class="atlas-leaf"><strong class="atlas-leaf">Plan(s)</strong></span><span class="atlas-leaf">”), in each case as offered by iDraft from time to time. This Agreement applies to anyone (“</span><span class="atlas-leaf"><strong class="atlas-leaf">You</strong></span><span class="atlas-leaf">”/”</span><span class="atlas-leaf"><strong class="atlas-leaf">Customer</strong></span><span class="atlas-leaf">”) who subscribes for or uses the Services to receive Content (as defined below).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">By subscribing to or using the Services, you agree to these terms. Please read them carefully as they set out the legal agreement between You (the Customer) and iDraft.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">THESE TERMS AND CONDITIONS (WHICH TOGETHER WITH THE APPLICABLE PLAN ARE COLLECTIVELY REFERRED TO AS THE “AGREEMENT”) CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION ON YOUR LEGAL RIGHTS, REPRESENTATIONS, WARRANTIES, CONDITIONS, REMEDIES, OBLIGATIONS AND LIABILITIES THAT ARE APPLICABLE TO THE SERVICES SO YOU SHOULD READ IT CAREFULLY BEFORE USING THE SERVICES. THE AGREEMENT TO ARBITRATE REQUIRES (WITH LIMITED EXCEPTION) THAT YOU SUBMIT CLAIMS YOU HAVE AGAINST iDraft TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST iDraft ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, (2) YOU WILL ONLY BE PERMITTED TO SEEK RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ON AN INDIVIDUAL BASIS, AND (3) YOU MAY NOT BE ABLE TO HAVE ANY CLAIMS YOU HAVE AGAINST iDraft RESOLVED BY A JURY OR IN A COURT OF LAW. EITHER BY CLICKING A BOX INDICATING YOUR ACCEPTANCE OR BY EXECUTING A PLAN THAT REFERENCES THIS AGREEMENT, YOU AGREE TO THIS AGREEMENT. IF YOU ARE AN AGENT OR EMPLOYEE OF AN ENTITY, YOU REPRESENT AND WARRANT THAT (I) THE INDIVIDUAL ACCEPTING THIS AGREEMENT IS AUTHORIZED TO ACCEPT THIS AGREEMENT ON SUCH ENTITY'S BEHALF AND TO BIND SUCH ENTITY, AND (II) SUCH ENTITY HAS FULL POWER, CORPORATE OR OTHERWISE, TO ENTER INTO THIS AGREEMENT AND PERFORM ITS OBLIGATIONS HEREUNDER. IF YOU DO NOT ACCEPT THIS AGREEMENT, THEN DO NOT USE THE SERVICES.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">Your Privacy: </strong></span><span class="atlas-leaf">iDraft respects the privacy of Customers. For more information please see iDraft’s Privacy Policy, located at </span><span class="atlas-leaf"><a href="/privacy-policy" class="atlas-leaf" target="_self"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">privacy-policy</u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf">, as applicable (the “Privacy Policy”). By using the Services, you consent to iDraft’s collection, use and disclosure of personal data and other data as outlined therein.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">1. Definitions</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">For the purposes of this Agreement, in addition to the capitalized terms defined elsewhere in this Agreement, the following terms shall have the meanings ascribed to them as follows:</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">“</span><span class="atlas-leaf"><strong class="atlas-leaf">Affiliate</strong></span><span class="atlas-leaf">” means any entity that directly or indirectly controls, is controlled by, or is under common control with the subject entity. “</span><span class="atlas-leaf"><strong class="atlas-leaf">Control</strong></span><span class="atlas-leaf">”, for purposes of this Agreement, means direct or indirect ownership or control of more than fifty percent (50%) of the voting interests of the subject entity;</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">“</span><span class="atlas-leaf"><strong class="atlas-leaf">Content</strong></span><span class="atlas-leaf">” means the requested content made available by iDraft to Customer through the Services;</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">“</span><span class="atlas-leaf"><strong class="atlas-leaf">Customer Data</strong></span><span class="atlas-leaf">” means all electronic data or information submitted by Customer and/or its Users to the Services;</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">“Fee”</strong></span><span class="atlas-leaf"> means the fees (as specified in the applicable Plan) payable by Customer to iDraft for the right to receive access to the Services;</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">“Malicious Code”</strong></span><span class="atlas-leaf"> means viruses, worms, time bombs, Trojan horses and other harmful or malicious code, files, scripts, agents or programs;</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">“Term”</strong></span><span class="atlas-leaf"> has the meaning ascribed to that term in Section 9.1; and</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">“User”</strong></span><span class="atlas-leaf"> means an individual or entity who is authorized by Customer to use the Services, and who has been supplied a user account and password by Customer (or by iDraft at Customer’s request) for the Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2. Provision and Use of the Services.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.1 Provision of Services.</strong></span><span class="atlas-leaf"> Subject to the terms and conditions of this Agreement including payment of the applicable fees, iDraft shall make the Services available to Customer for Customer’s internal business use during the Term. Customer’s right to use the Services during the Term shall be in accordance with any additional conditions, restrictions or parameters specified in the applicable Plan(s).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.2 User Accounts.</strong></span><span class="atlas-leaf"> User accounts are for use by designated Users and cannot be shared or used by more than one User but may be reassigned to new Users replacing former Users who no longer require ongoing use of the Services. If Customer chooses to register for the Services, Customer will, and will ensure that its Users, provide and maintain true, accurate, current, and complete information about themselves as prompted by the User accounts. Registration data and certain other information about Customers, and/or its Users, are governed by iDraft’s Privacy Policy. If a User is under 16 years of age, that User is not authorized to use the Services, with or without registering. Customer is responsible for maintaining, and will ensure that its Users maintain, the confidentiality of each User’s password and account details, if any, and Customer and the applicable User are fully responsible for any and all activities that occur under the applicable User’s password or account. Customer agrees, and will ensure that its Users agree, to (i) immediately notify iDraft of any unauthorized use of a User’s password or account or any other breach of security, and (ii) ensure that the User exits from User’s account at the end of each session when accessing the Services. iDraft will not be liable for any loss or damage arising from Customer’s, or its Users’, failure to comply with this paragraph.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.3 Content and Content Providers</strong></span><span class="atlas-leaf">. iDraft engages independent third party content providers (“Content Providers”) in order to develop the Content. Content Providers are contractually bound to maintain the confidentiality of all Customer materials that they may receive through iDraft. The Content provided through the Services is based on iDraft’s reasonable efforts to engage with responsible and reputable Content Providers at any given time, but all Content is provided on an “As-Is” basis. iDraft makes no representation or warranty regarding the Content, whether in regards to its accuracy, originality, suitability, non-infringement or otherwise. Subject to Section 4.6, iDraft may (but is not required to) submit any Content to a third-party verification tool such as Copyscape to assist in identifying any plagiarism or other intellectual property infringement by Content Providers, but iDraft accepts no responsibility for either failing to do so or for such third party tools failing to identify any such plagiarism or other intellectual property infringement, and iDraft accepts no responsibility for any infringement by any Content of any third party rights, whether arising due to intellectual property infringement (including without limitation plagiarism) or otherwise. Customer is solely responsible for the review and approval of any and all Content prior to Customer’s use or publication. Customer is solely responsible for any decision or action that it may take, regarding the use, publication or distribution of any Content, and iDraft accepts no responsibility for any consequences arising from such use, publication or distribution by Customer (including without limitation any claim for plagiarism, royalties or otherwise).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.4 Customer.</strong></span><span class="atlas-leaf"> Customer is responsible for all activities that occur in User accounts and for Users’ compliance with this Agreement. Customer shall: (i) have sole responsibility for the accuracy, quality, integrity, legality, reliability, and appropriateness of all Customer Data; (ii) use commercially reasonable efforts to prevent unauthorized access to, or use of, the Services, and notify iDraft promptly of any such unauthorized access or use; and (iii) comply with all applicable local, provincial, state, federal and foreign laws related to the Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.5 Use Guidelines.</strong></span><span class="atlas-leaf"> Customer shall not: (i) license, sublicense, sell, resell, rent, lease, transfer, assign, distribute, time share or otherwise commercially exploit or make the Services available to any third party; (ii) use the Services to send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (iii) use the Services to send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material that is harmful to children or violates third-party privacy or publicity rights; (iv) use the Services to send or store Malicious Code; (v) interfere with or disrupt the integrity or performance of the Services or the data contained therein; or (vi) attempt to gain unauthorized access to the Services or its related systems or networks.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">2.6 Publicity.</strong></span><span class="atlas-leaf"> Neither party may issue press releases relating to this Agreement without the other party's prior written consent. Each party may include the name and logo of the other party in lists of customers or vendors in accordance with the other party's standard guidelines.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3. FEES AND PAYMENT.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.1 Fees.</strong></span><span class="atlas-leaf"> In consideration for the receipt of the Services, Customer shall pay iDraft the Fees specified in the applicable Plan. iDraft reserves the right to amend the Fees on not less than 60 days’ advance notice in writing to Customer. Except as set forth herein, all payment obligations are non-cancelable and non-pro-ratable for partial months, and fees paid are non-refundable.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.2 Invoicing and Payment.</strong></span><span class="atlas-leaf"> Fees for the Services will be invoiced monthly in advance or as otherwise as specified in the applicable Plan. Unless otherwise stated in an invoice, charges are due immediately on the invoice date. Customer is responsible for maintaining complete and accurate billing and contact information with iDraft.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.3 Overdue Payments.</strong></span><span class="atlas-leaf"> Any payment not received from Customer by the due date may accrue (except with respect to charges then under reasonable and good faith dispute), at iDraft's discretion, late charges at the rate of 1.0% of the outstanding balance per month (12.67% per annum), or the maximum rate permitted by law, whichever is lower, from the date such payment was due until the date paid.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.4 Taxes.</strong></span><span class="atlas-leaf"> Unless otherwise stated, iDraft's Fees do not include any direct or indirect local, state, provincial, federal or foreign taxes, levies, duties or similar governmental assessments of any nature, including value-added, goods and services, harmonized, use or withholding taxes (collectively, "</span><span class="atlas-leaf"><strong class="atlas-leaf">Taxes</strong></span><span class="atlas-leaf">"). Customer is responsible for paying all Taxes associated with its purchases hereunder, excluding taxes based on iDraft's net income or property. If iDraft has the legal obligation to pay or collect Taxes for which Customer is responsible under this section, the appropriate amount shall be invoiced to and paid by Customer, unless Customer provides iDraft with a valid tax exemption certificate authorized by the appropriate taxing authority.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.5 Audit Rights. </strong></span><span class="atlas-leaf">iDraft shall have the right to use the capabilities of the Services to monitor the use of the Services and Customer’s compliance with this Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.6 Suspension of Services.</strong></span><span class="atlas-leaf"> If Customer's account is overdue (except with respect to charges then under reasonable and good faith dispute), in addition to any of its other rights or remedies, iDraft reserves the right to suspend the Services provided to Customer, without liability to Customer, until such amounts are paid in full.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">3.7 Validity.</strong></span><span class="atlas-leaf"> Upon every charge to the Customer's card, the Customer will receive a word quota as specified in the applicable Plan. This word quota will be valid for a duration of one (1) year from the date of the last charge. Any unused word quota will expire and be forfeited at the end of this one-year period. It is the responsibility of the Customer to utilize their word quota within the stipulated validity period.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">4. NON-CIRCUMVENTION</strong></span><span class="atlas-leaf">.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">4.1Payments Through iDraft.</strong></span><span class="atlas-leaf"> With respect to each Content Provider identified or to which Customer is connected via the Services, for the term of Customer’s connection or other relationship with such Content Provider in relation to the Services, and for 12 months thereafter (with respect to each such Content Provider, the “Non-Circumvention Period”), Customer agrees to use the Services as the Customer’s exclusive method to request Content from such Content Provider and make payments for work to such Content Provider. If Customer uses the Services as an employee, agent, or representative of an entity, then the Non-Circumvention Period and restrictions above apply with respect to such Customer and the other employees, agents, or representatives of such entity or its successor when acting in that capacity. If Customer is aware of a breach or potential breach of this non-circumvention provision, Customer will submit a confidential report to iDraft at </span><span class="atlas-leaf"><a href="mailto:support@<?=$ihost?>" class="atlas-leaf" target="_blank"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">support@<?=$ihost?></u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf">.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">4.2Communication Through iDraft</strong></span><span class="atlas-leaf">. With respect to each Content Provider identified or to which Customer is connected via the Services, during the Non-Circumvention Period applicable to such Content Provider, Customer (i) will use the Services as the sole manner to communicate with such Content Provider; (ii) will not provide contact information (including any phone number, email address, physical address, social media handles, or other communication methods and tools) (hereinafter, “Contact Information”) of Customer to such Content Provider; (iii) will not use any Contact Information of such Content Provider to communicate with, solicit, contact, or find such Content Provider outside of the Services; (iv) will not ask for, provide, or attempt to identify through public means the Contact Information of such Content Provider; and (v) will not include any of Customer’s Contact Information or means by which any of Customer’s Contact Information could be discovered in Customer’s User account, except as otherwise provided by iDraft.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">4.3 Breach of Non-Circumvention</strong></span><span class="atlas-leaf">. Customer understands and agrees that if iDraft, in its sole discretion, determines that Customer has violated this Section 4, iDraft may, at its option, (i) terminate Customer’s User account and/or suspend Customer’s use the Services, and/or (ii) charge Customer for all losses and costs (including any and all time of iDraft’s internal workforce) and reasonable expenses (including attorneys’ fees) related to investigating such breach and collecting such fees. This Section 4 still applies if Customer chooses to cease using the Services and wishes to continue working with a Content Provider after Customer ceases using the Services. Customer agrees to notify iDraft immediately if any person suggests making or receiving payments other than through the Services in violation of this Section 4 or if Customer receives unsolicited contact outside of the Services. Customer acknowledges and agrees that a violation of Section 4 is a material breach of this Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5. OWNERSHIP RIGHTS.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.1 Rights to Content</strong></span><span class="atlas-leaf">. iDraft hereby assigns all of its right, title and interest in and to the Content (including the copyrights in the Content) to Customer on delivery of such Content to Customer and payment of all corresponding Fees by the Customer. All moral rights to Content are waived by iDraft and the Content Providers.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.2 Rights to the Services.</strong></span><span class="atlas-leaf"> Subject to the limited rights expressly granted hereunder, iDraft reserves all rights, title and interest in and to the Services, including all related intellectual property rights therein. No rights are granted to Customer hereunder other than as expressly set forth in this Agreement. Customer and its Users are permitted to access the Services solely for Customer’s internal business purposes.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.3 Restrictions.</strong></span><span class="atlas-leaf"> Customer shall not (and shall not allow any third party to): (i) modify, translate, reverse engineer, decompile, disassemble, or create derivative works based on the Services except to the extent that enforcement is prohibited by applicable law notwithstanding a contractual provision to the contrary; (ii) circumvent any user limits or other timing or use restrictions that are built into the Services; (iii) remove any proprietary notices, labels, or marks from the Services; (iv) frame or mirror any content forming part of the Services; (v) access the Services in order to (A) build a competitive product or service, or (B) copy any ideas, features, functions or graphics of the Services; or (vi) otherwise use the Services in violation of applicable law (including any export law) or outside the scope expressly permitted under this Agreement. Customer may use the Content or any excerpt from the Content to promote its products or services. External citation to the Content is prohibited without iDraft’s express written permission.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.4 Customer Data.</strong></span><span class="atlas-leaf"> As between iDraft and Customer, Customer exclusively owns all rights, title and interest in and to all Customer Data. Customer Data is deemed Customer’s Confidential Information under this Agreement. iDraft shall not access Customer's User accounts, including Customer Data, except to respond to service or technical problems or at Customer's request or as necessary for the operation of the Services or billing. Customer hereby grants iDraft a non-exclusive, non-transferable (except in connection with the permitted assignment of this Agreement), irrevocable, sublicensable (through multiple tiers), worldwide, royalty-free, fully paid-up, perpetual license to use, aggregate, collect, analyze and otherwise exploit the Customer Data, Content and other information relating to the performance of the Services and iDraft shall be free (during and after the Term) to (i) use such Customer Data, Content and other information to improve and provide iDraft’s products and services, and (ii) disclose such Customer Data, Content and other information solely in an aggregated and anonymized format that does not identify Customer or any individual (“Aggregated Data”). iDraft shall own all Aggregated Data created from the Customer Data and Content.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.5 Suggestions</strong></span><span class="atlas-leaf">. iDraft shall have a royalty-free, worldwide, transferable, sublicensable (through multiple tiers), irrevocable, perpetual, unrestricted license to use or incorporate into the Services and/or any other products or services any suggestions, enhancement requests, recommendations or other feedback provided by Customer or its Users relating to the Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">5.6 Third-Party Services.</strong></span><span class="atlas-leaf"> The Services may provide links or other access to services, sites, technology, and resources that are provided or otherwise made available by third parties (the “Third-Party Services”). Additionally, Customer may enable or log in to the Services via various online Third-Party Services, such as social media and social networking services. Customer’s access and use of the Third-Party Services may also be subject to additional terms and conditions, privacy policies, or other agreements with such third party, and Customer may be required to authenticate to or create separate accounts to use Third-Party Services on the websites or via the technology platforms of their respective providers. Some Third-Party Services will provide iDraft with access to certain information that Customer has provided to third parties, including through such Third-Party Services, and iDraft will use, store and disclose such information in accordance with our Privacy Policy. For more information about the implications of activating Third-Party Services and iDraft’s use, storage and disclosure of information related to Customer and Customer’s use of such Third-Party Services within the Service, please see our Privacy Policy. iDraft has no control over and is not responsible for such Third-Party Services, including for the accuracy, availability, reliability, or completeness of information shared by or available through Third-Party Services, or on the privacy practices of Third-Party Services. iDraft encourages Customer to review the privacy policies of the third parties providing Third-Party Services prior to using such services. Customer, and not iDraft, will be responsible for any and all costs and charges associated with Customer’s use of any Third-Party Services. iDraft enables these Third-Party Services merely as a convenience and the integration or inclusion of such Third-Party Services does not imply an endorsement or recommendation. Any dealings Customer has with third parties while using the Services are between Customer and the third party. iDraft will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any Third-Party Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6. CONFIDENTIALITY</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6.1 Definition of Confidential Information.</strong></span><span class="atlas-leaf"> As used herein, </span><span class="atlas-leaf"><strong class="atlas-leaf">“Confidential Information”</strong></span><span class="atlas-leaf"> means all confidential and proprietary information of a party (the </span><span class="atlas-leaf"><strong class="atlas-leaf">“Disclosing Party”</strong></span><span class="atlas-leaf">) disclosed to the other party (the </span><span class="atlas-leaf"><strong class="atlas-leaf">“Receiving Party”</strong></span><span class="atlas-leaf">), whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure, including the terms and conditions of this Agreement, pricing and other terms reflected in the applicable Plan hereunder, the Services, business and marketing plans, technology and technical information, product designs, and business processes. Confidential Information shall not include any information that: (i) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party; (ii) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (iii) was independently developed by the Receiving Party without breach of any obligation owed to the Disclosing Party; or (iv) is received from a third party without breach of any obligation by the Receiving Party or such third party owed to the Disclosing Party.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6.2 Confidentiality.</strong></span><span class="atlas-leaf"> The Receiving Party shall not disclose or use any Confidential Information of the Disclosing Party for any purpose outside the scope of this Agreement, except with the Disclosing Party's prior written permission.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6.3 Protection.</strong></span><span class="atlas-leaf"> Each party agrees to protect the confidentiality of the Confidential Information of the other party in the same manner that it protects the confidentiality of its own proprietary and confidential information of like kind (but in no event using less than reasonable care).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6.4 Compelled Disclosure</strong></span><span class="atlas-leaf">. If the Receiving Party is compelled by law to disclose Confidential Information of the Disclosing Party, it shall provide the Disclosing Party with prior notice of such compelled disclosure (to the extent legally permitted) and reasonable assistance, at the Disclosing Party's cost, if the Disclosing Party wishes to contest the disclosure.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">6.5 Remedies.</strong></span><span class="atlas-leaf"> If the Receiving Party discloses or uses (or threatens to disclose or use) any Confidential Information of the Disclosing Party in breach of confidentiality protections in this Agreement, the Disclosing Party shall have the right, in addition to any other remedies available to it, to seek injunctive relief to enjoin such acts, it being specifically acknowledged by the parties that any other available remedies may be inadequate.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">7. WARRANTIES AND DISCLAIMERS.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">7.1 Warranties.</strong></span><span class="atlas-leaf"> Each party warrants that it has the legal power to enter into this Agreement. Customer represents, warrants and agrees that (i) Customer has all rights necessary to provide any Customer Data that it provides hereunder, and to permit iDraft to use the same as contemplated hereunder; and (ii) all information that Customer provides to iDraft, including without limitation the Customer Data, are complete, true and accurate.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">7.2 Disclaimer.</strong></span><span class="atlas-leaf"> EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, iDraft MAKES NO REPRESENTATIONS AND PROVIDES NO WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND SPECIFICALLY DISCLAIMS ALL IMPLIED REPRESENTATIONS, WARRANTIES AND/OR CONDITIONS, INCLUDING ANY REPRESENTATIONS, WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, MERCHANTABLE QUALITY, DURABILITY, TITLE, NON-INFRINGEMENT, SATISFACTORY QUALITY OR FITNESS FOR A PARTICULAR PURPOSE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. TO THE MAXIMUM EXTENT PERMITTED BY LAW, iDraft FURTHER DISCLAIMS ALL WARRANTIES (I) RELATING TO THE ACCURACY, RELIABILITY, CORRECTNESS, OR COMPLETENESS OF THE CONTENT OR ANY PORTION THEREOF THAT IS MADE AVAILABLE THROUGH THE SERVICES; (II) THAT THE CONTENT PROVIDED THROUGH THE SERVICES WILL BE FREE FROM ERRORS, OMISSIONS, DEFECTS, OR DELAYS IN OPERATION, OR FROM TECHNICAL INACCURACIES OR OTHER ERRORS; (III) THAT THE CONTENT OR SERVICES SHALL NOT INFRINGE THE INTELLECTUAL PROPERTY OR PROPRIETARY RIGHTS OF ANY THIRD PARTY; (IV) THAT THE CONTENT OR SERVICES WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (V) THAT THE SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">8. INDEMNIFICATION</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">8.1 Indemnification by Customer.</strong></span><span class="atlas-leaf"> Customer shall, at its own expense, defend, indemnify and hold harmless iDraft, its Affiliates and its and their directors, officers, employees and agents (the “iDraft Indemnitees”) against all losses, damages, expenses or costs (including but not limited to reasonable attorneys' fees) arising in connection with any action, suit or proceeding brought by a third party against any of the iDraft Indemnitees alleging that the Customer Data, or Customer's use of the Content or Services infringes or misappropriates the intellectual property or other rights of, or has otherwise harmed, a third party (</span><span class="atlas-leaf"><strong class="atlas-leaf">“Customer Claims”</strong></span><span class="atlas-leaf">). iDraft shall (i) notify Customer promptly in writing upon becoming aware of all pending Customer Claims; (ii) give Customer sole control of the defense and settlement of such Customer Claims; and (iii) cooperate with Customer in the defense or settlement of such Customer Claims; provided that iDraft’s failure to do any of the foregoing will not limit Customer’s obligations except to the extent Customer is materially prejudiced thereby. Customer shall not settle any Customer Claims without iDraft’s written consent, or compromise the defense of any such Customer Claims or make any admissions in respect thereto.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">9 LIMITATION OF LIABILITY</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">9.1 Limitation of Liability.</strong></span><span class="atlas-leaf"> IN NO EVENT SHALL EITHER PARTY'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED THE LESSER OF $500 OR THE AMOUNTS ACTUALLY PAID BY AND DUE FROM CUSTOMER HEREUNDER IN THE TWO MONTHS PRECEDING THE INCIDENT GIVING RISE TO LIABILITY.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">9.2 Exclusion of Consequential and Related Damages.</strong></span><span class="atlas-leaf"> IN NO EVENT SHALL EITHER PARTY HAVE ANY LIABILITY TO THE OTHER PARTY FOR ANY LOST PROFITS OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOST SAVINGS OR OTHER SIMILAR PECUNIARY LOSS) HOWEVER CAUSED AND, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR UNDER ANY OTHER THEORY OF LIABILITY, WHETHER OR NOT THE PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">9.3 Certain Damages Not Excluded.</strong></span><span class="atlas-leaf"> NOTWITHSTANDING THE FOREGOING, NO LIMITATION OF EITHER PARTY’S LIABILITY SET FORTH IN THIS AGREEMENT SHALL APPLY TO (I) DAMAGES ARISING FROM ANY INFRINGEMENT AND/OR MISAPPROPRIATION OF THE OTHER PARTY’S INTELLECTUAL PROPERTY RIGHTS; (II) ANY CLAIMS FOR NON-PAYMENT; OR (III) ANY CLAIM UNDER SECTION 7 (INDEMNIFICATION).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">9.4 Beneficiaries.</strong></span><span class="atlas-leaf"> Every right, exemption from liability, release, defense, immunity and waiver of whatsoever nature applicable to a party under this Agreement shall also be available and shall extend to benefit and to protect such party’s Affiliates, subcontractors, agents, licensors, suppliers, directors and/or employees and for such purposes such party is or shall be deemed to be acting as agent or trustee on behalf of and for the benefit of such companies and persons in respect to such rights, exemptions, releases, defenses, immunities and waivers.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10. TERM AND TERMINATION.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10.1 Term of Agreement.</strong></span><span class="atlas-leaf"> This Agreement shall commence as of the Effective Date and shall continue in effect on a month-by-month basis unless otherwise specified in the applicable Plan. Subject to any minimum term in the applicable Plan, either party may terminate this Agreement without cause on not less than 30 days’ prior notice, or by otherwise following any termination mechanism provided for within the Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10.2 Termination for Cause.</strong></span><span class="atlas-leaf"> A party may terminate this Agreement for cause: (i) upon thirty (30) days written notice of a material breach to the other party if such breach remains uncured at the expiration of such period; or (ii) if the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, receivership, liquidation or assignment for the benefit of creditors. Upon any termination for cause under this Section 9.2 by Customer (but not otherwise), iDraft may refund Customer on a pro-rata basis any prepaid fees for, in the case of a Subscription Plan, any periods after the termination of the Agreement or, in the case of a Usage Plan, any unused credits.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10.3 Termination by iDraft</strong></span><span class="atlas-leaf">. Customer agrees that iDraft, in its sole discretion, may suspend or terminate Customer’s account (or any of its Users’ accounts) or use of the Services and remove and discard any Content within the Services, for any reason, including for lack of use or if iDraft believes that Customer has violated or acted inconsistently with the letter or spirit of this Agreement. Any suspected fraudulent, abusive, or illegal activity that may be grounds for termination of Customer’s use of the Services, may be referred to appropriate law enforcement authorities. iDraft may also in its sole discretion and at any time discontinue providing the Services, or any part thereof, with or without notice. Customer agrees that any termination of Customer’s access to the Services under any provision of this Agreement may be effected without prior notice, and acknowledges and agrees that iDraft may immediately deactivate or delete Customer’s account (or any of its Users’ accounts) and all related information and files in Customer’s User account and/or bar any further access to such files or the Services. Further, Customer agrees that iDraft will not be liable to Customer or any third party for any termination of Customer’s access to the Services. </span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10.4 Outstanding Fees.</strong></span><span class="atlas-leaf"> Termination or expiration of this Agreement shall not relieve Customer of the obligation to pay any Fees accrued or payable to iDraft prior to the effective date of termination or expiration of this Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">10.5 Surviving Provisions.</strong></span><span class="atlas-leaf"> The following provisions shall survive any termination or expiration of this Agreement: Sections 5 through 12.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11. Dispute Resolution By Binding Arbitration.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.1 Agreement to Arbitrate. </strong></span><span class="atlas-leaf">This Dispute Resolution by Binding Arbitration section is referred to in this Agreement as the “Arbitration Agreement.” Customer agrees that any and all disputes or claims that have arisen or may arise between Customer and iDraft, whether arising out of or relating to this Agreement (including any alleged breach thereof), the Services, or any aspect of the relationship or transactions between the parties, will be resolved exclusively through final and binding arbitration, rather than a court, in accordance with the terms of this Arbitration Agreement, except that Customer may assert individual claims in small claims court, if Customer’s claims qualify. Further, this Arbitration Agreement does not preclude Customer from bringing issues to the attention of federal, state, or local agencies, and such agencies can, if the law allows, seek relief against iDraft on Customer’s behalf. Customer agrees that, by entering into this Agreement, Customer and iDraft are each waiving the right to a trial by jury or to participate in a class action. Customer’s rights will be determined by a neutral arbitrator, not a judge or jury. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.2 Prohibition of Class and Representative Actions and Non-Individualized Relief</strong></span><span class="atlas-leaf">. </span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><em class="atlas-leaf"><strong class="atlas-leaf">CUSTOMER AND iDraft AGREE THAT EACH OF THE PARTIES MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH CUSTOMER AND iDraft AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON’S OR PARTY’S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY’S INDIVIDUAL CLAIM(S), EXCEPT THAT YOU MAY PURSUE A CLAIM FOR AND THE ARBITRATOR MAY AWARD PUBLIC INJUNCTIVE RELIEF UNDER APPLICABLE LAW TO THE EXTENT REQUIRED FOR THE ENFORCEABILITY OF THIS PROVISION.</strong></em></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.3 Pre-Arbitration Dispute Resolution</strong></span><span class="atlas-leaf">. iDraft is always interested in resolving disputes amicably and efficiently, and most Customer concerns can be resolved quickly and to the Customer’s satisfaction by emailing customer support at </span><span class="atlas-leaf"><a href="mailto:support@<?=$ihost?>" class="atlas-leaf" target="_blank"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">support@<?=$ihost?></u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf">. If such efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute (“Notice”). The Notice to iDraft should be sent to </span><span class="atlas-leaf"><a href="mailto:john@<?=$ihost?>" class="atlas-leaf" target="_blank"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">john@<?=$ihost?></u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf"> (“Notice Address”). The Notice must (i) describe the nature and basis of the claim or dispute and (ii) set forth the specific relief sought. If iDraft and Customer do not resolve the claim within sixty (60) calendar days after the Notice is received, Customer or iDraft may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by iDraft or Customer will not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which Customer or iDraft is entitled.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.4 Arbitration Procedures</strong></span><span class="atlas-leaf">. Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Association’s (“AAA”) rules and procedures, including the AAA’s Consumer Arbitration Rules (collectively, the “AAA Rules”), as modified by this Arbitration Agreement. For information on the AAA, please visit its website, </span><span class="atlas-leaf"><a href="http://www.adr.org/" class="atlas-leaf" target="_blank"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">http://www.adr.org</u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf">. Information about the AAA Rules and fees for consumer disputes can be found at the AAA’s consumer arbitration page, </span><span class="atlas-leaf"><a href="https://www.adr.org/consumer" class="atlas-leaf" target="_blank"><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span><u class="atlas-leaf">https://www.adr.org/consumer</u><span contenteditable="false" style="font-size: 0px; line-height: 0;">&nbsp;</span></a>
                                </span><span class="atlas-leaf">. If there is any inconsistency between any term of the AAA Rules and any term of this Arbitration Agreement, the applicable terms of this Arbitration Agreement will control unless the arbitrator determines that the application of the inconsistent Arbitration Agreement terms would not result in a fundamentally fair arbitration. The arbitrator must also follow the provisions of this Agreement as a court would. All issues are for the arbitrator to decide, including issues relating to the scope, enforceability, and arbitrability of this Arbitration Agreement. Although arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings, the arbitrator can award the same damages and relief on an individual basis that a court can award to an individual under this Agreement and applicable law. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf">Unless iDraft and Customer agree otherwise, any arbitration hearings will take place in a reasonably convenient location for both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, the determination will be made by AAA. If Customer’s claim is for $10,000 or less, iDraft agrees that Customer may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules. If Customer’s claim exceeds $10,000, the right to a hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator will issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.5 Costs of Arbitration</strong></span><span class="atlas-leaf">. Payment of all filing, administration, and arbitrator fees (collectively, the “Arbitration Fees”) will be governed by the AAA Rules, unless otherwise provided in this Arbitration Agreement. To the extent any Arbitration Fees are not specifically allocated to either iDraft or Customer under the AAA Rules, iDraft and Customer shall split them equally; provided that if Customer is able to demonstrate to the arbitrator that Customer is economically unable to pay Customer’s portion of such Arbitration Fees or if the arbitrator otherwise determines for any reason that Customer should not be required to pay Customer’s portion of any Arbitration Fees, iDraft will pay Customer’s portion of such fees. In addition, if Customer demonstrates to the arbitrator that the costs of arbitration will be prohibitive as compared to the costs of litigation, iDraft will pay as much of the Arbitration Fees as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive. Any payment of attorneys’ fees will be governed by the AAA Rules.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.6 Confidentiality</strong></span><span class="atlas-leaf">. All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.7 Severability</strong></span><span class="atlas-leaf">. If a court or the arbitrator decides that any term or provision of this Arbitration Agreement (other than Section 10.2 titled “Prohibition of Class and Representative Actions and Non-Individualized Relief” above) is invalid or unenforceable, the parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement will be enforceable as so modified. If a court or the arbitrator decides that any of the provisions of Section 10.2 above titled “Prohibition of Class and Representative Actions and Non-Individualized Relief” are invalid or unenforceable, then the entirety of this Arbitration Agreement will be null and void, unless such provisions are deemed to be invalid or unenforceable solely with respect to claims for public injunctive relief. The remainder of this Agreement will continue to apply.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">11.8 Future Changes to Arbitration Agreement. </strong></span><span class="atlas-leaf">Notwithstanding any provision in this Agreement to the contrary, iDraft agrees that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while Customer is a user of the Services, Customer may reject any such change by sending iDraft written notice within thirty (30) calendar days of the change to the Notice Address provided above. By rejecting any future change, Customer is agreeing that Customer will arbitrate any dispute between the parties in accordance with the language of this Arbitration Agreement as of the date Customer first accepted this Agreement (or accepted any subsequent changes to this Agreement).</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12. GENERAL PROVISIONS.</strong></span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.1 Relationship of the Parties.</strong></span><span class="atlas-leaf"> The parties are independent contractors. This Agreement does not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.2 No Third-Party Beneficiaries.</strong></span><span class="atlas-leaf"> Except as expressly provided in this Agreement, there are no third-party beneficiaries to this Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.3 Notices.</strong></span><span class="atlas-leaf"> All notices under this Agreement shall be in writing and shall be deemed to have been given upon: (i) personal delivery; (ii) the second business day after mailing; (iii) the second business day after sending by confirmed facsimile; or (iv) the second business day after sending by email. Notices to iDraft shall be addressed to the attention of the Legal Department. Notices to Customer shall be addressed to Customer’s signatory of this Agreement unless otherwise designated below.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.4 Waiver and Cumulative Remedies.</strong></span><span class="atlas-leaf"> No failure or delay by either party in exercising any right under this Agreement shall constitute a waiver of that right. Other than as expressly stated herein, the remedies provided herein are in addition to, and not exclusive of, any other remedies of a party at law or in equity.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.5 Severability</strong></span><span class="atlas-leaf">. If any provision of this Agreement is held by a court of competent jurisdiction to be contrary to law, the provision shall be modified by the court and interpreted so as best to accomplish the objectives of the original provision to the fullest extent permitted by law, and the remaining provisions of this Agreement shall remain in effect. To the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof will be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability and will be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the parties. The illegality, invalidity, or unenforceability of such provision in one jurisdiction will not in any way affect the legality, validity, or enforceability of that or any other provision in any other jurisdiction.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.6 Assignment.</strong></span><span class="atlas-leaf"> Neither party may assign any of its rights or obligations hereunder, whether by operation of law or otherwise, without the prior written consent of the other party (not to be unreasonably withheld). Notwithstanding the foregoing, each party may assign this Agreement in its entirety (including all Plans), without consent of the other party, to an Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its business, stock or assets. Any attempt by a party to assign its rights or obligations under this Agreement in breach of this section shall be void and of no effect. Subject to the foregoing, this Agreement shall bind and inure to the benefit of the parties, their respective successors and permitted assigns.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.7 Governing Law.</strong></span><span class="atlas-leaf"> This Agreement shall be governed by the laws of the Province of Ontario, Canada, without regard to its conflict of law principles. No choice of laws rules of any jurisdiction shall apply to this Agreement. The application of the United Nations Convention on Contracts for the International Sale of Goods to this Agreement is expressly excluded. The parties confirm that it is their wish that this Agreement as well as all other documents relating to this Agreement, including notices, be drawn up in English only. </span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.8 Venue; Waiver of Jury Trial.</strong></span><span class="atlas-leaf"> The provincial and federal courts located in Toronto, Ontario, Canada, shall have exclusive jurisdiction to adjudicate any dispute arising out of or relating to this Agreement. Each party hereby consents to the exclusive jurisdiction of such courts. Each party also hereby waives any right to jury trial in connection with any action or litigation in any way arising out of or related to this Agreement.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.9 Force Majeure.</strong></span><span class="atlas-leaf"> Neither party shall be responsible for its failure to perform to the extent due to unforeseen circumstances or causes beyond its control, including but not limited to acts of God, wars, terrorism, riots, embargoes, acts of civil or military authorities, fires, floods, accidents, or strikes, labour problems (other than those involving the employees of the affected party), computer, telecommunications, Internet service iDraft or hosting facility failures or delays involving hardware, software or power systems not within a party’s possession or reasonable control, provided that such party gives the other party prompt written notice of the failure to perform and the reason therefore and uses its reasonable efforts to limit the resulting delay in its performance.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.10 Export.</strong></span><span class="atlas-leaf"> Customer acknowledges and agrees that the Services may be subject to export and import controls under the regulations of Canada, the United States and other countries, and Customer shall comply with all export and import control regulations of such countries. Customer shall not use the Services for any purposes prohibited by export laws, including, without limitation, nuclear, chemical or biological weapons proliferation. Customer shall be responsible for procuring all required permissions for any subsequent export, import or use of the Services.</span></p>
                            <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"><strong class="atlas-leaf">12.11 Entire Agreement.</strong></span><span class="atlas-leaf"> This Agreement constitutes the entire agreement between the parties, and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. No modification, amendment, or waiver of any provision of this Agreement shall be effective unless in writing and signed by the party against whom the modification, amendment or waiver is to be asserted. To the extent of any conflict or inconsistency between the provisions in the body of this Agreement and the applicable Plan, the terms of this Agreement prevail unless otherwise expressly provided for in the applicable Plan. Notwithstanding any language to the contrary therein, no terms or conditions stated in any third party purchase order or in any other third party order documentation shall be incorporated into or form any part of this Agreement, and all such terms or conditions shall be null and void.</span></p>
                            <p class="atlas-block atlas-block-paragraph">
                                <p class="atlas-block atlas-block-paragraph"><span class="atlas-leaf"></span></p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="pt-[80px] pb-[80px] relative z-[20] text-[black] bg-[white] bg-cover bg-repeat-x bg-scroll bg-top bg-[#FFFFFF] bg-opacity-[100%] text-[#000000] text-opacity-[100%]" style="background-image: url(https://assets.ycodeapp.com/assets/app18099/Images/Uq0gLePc4Nw40SP0RpxwOZuIrVJ2n4rXeVHIFsSP.png)">
                <div class="max-w-[80rem] mt-[0] mr-[auto] mb-[0] ml-[auto] pt-[0] pr-[32px] pb-[0] pl-[32px] md:pr-[24px] md:pl-[24px]">
                    <div class="max-w-[80rem] mt-[0] mr-[auto] mb-[0] ml-[auto] pt-[0] pr-[32px] pb-[0] pl-[32px] md:pr-[24px] md:pl-[24px] xl:pr-[40px] xl:pl-[40px] bg-bottom">
                        <div class="flex items-center justify-center flex-wrap mb-[20px] gap-[40px] text-[black] text-[#000000] text-opacity-[100%]"> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[black] text-[#000000] text-opacity-[100%]" href="/terms-of-service">Terms Of Service</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[black] text-[#000000] text-opacity-[100%]" href="/privacy-policy">Privacy Policy</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[black] text-[#000000] text-opacity-[100%]" href="/refund-policy">Refund policy</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[black] text-[#000000] text-opacity-[100%]" href="/delivery-policy">delivery policy</a> <a class="focus:outline-none no-underline text-[16px] font-medium hover:text-opacity-[50%] text-[black] text-[#000000] text-opacity-[100%]" href="/about-us">about us</a></div> <span class="text-[12px] block text-center sm:text-center tracking-[0.1em] uppercase text-[black] text-[#000000] text-opacity-[100%]">© 2023 CONTENTFLY INC.  All rights reserved.</span></div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.ycode.com/yc/js/swiper-bundle.min.js"></script>
    <script src="https://cdn.ycode.com/yc/js/gsap-latest-beta.min.js"></script>
    <script src="https://cdn.ycode.com/yc/js/ScrollTrigger.min.js"></script>
    <script src="/js/generated.js?id=c47dd6a59ab2895a0db6"></script>
</body>
</html>